#!/usr/bin/perl

use Getopt::Std;

getopts('f:n:l:');

#print("OPT F: $opt_f\n");
#print("OPT N: $opt_n\n");

open $INFILE, $opt_f or die "$!\nFILE $opt_f";

while (<$INFILE>){
    system($_);
}

close $INFILE;
