/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.boisestate.SimSearcher;

import javax.swing.JPanel;

public final class ClusteringVisualPanel1 extends JPanel {
    
    private String lastDir;

    /**
     * Creates new form ClusteringVisualPanel1
     */
    public ClusteringVisualPanel1() {
        initComponents();
        lastDir = System.getProperty("user.home");
        for(String dist_metric : SimSearchUtilities.similarity_metrics){
            distTestComboBox.addItem(dist_metric);
        }
    }

    @Override
    public String getName() {
        return "Clustering Parameters";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapDirButton = new javax.swing.JButton();
        outputDirButton = new javax.swing.JButton();
        mapDirTxtField = new javax.swing.JTextField();
        outputDirTxtField = new javax.swing.JTextField();
        distTestComboBox = new javax.swing.JComboBox();
        numNodesTxtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        clusters_1TxtField = new javax.swing.JTextField();
        clusters_2TxtField = new javax.swing.JTextField();
        clusters_3TxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        swrmCmdOptsTxtField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jobsPerNodeTxtField = new javax.swing.JTextField();
        verboseChkBox = new javax.swing.JCheckBox();

        org.openide.awt.Mnemonics.setLocalizedText(mapDirButton, org.openide.util.NbBundle.getMessage(ClusteringVisualPanel1.class, "ClusteringVisualPanel1.mapDirButton.text")); // NOI18N
        mapDirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapDirButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(outputDirButton, org.openide.util.NbBundle.getMessage(ClusteringVisualPanel1.class, "ClusteringVisualPanel1.outputDirButton.text")); // NOI18N
        outputDirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputDirButtonActionPerformed(evt);
            }
        });

        mapDirTxtField.setEditable(false);
        mapDirTxtField.setText(org.openide.util.NbBundle.getMessage(ClusteringVisualPanel1.class, "ClusteringVisualPanel1.mapDirTxtField.text")); // NOI18N

        outputDirTxtField.setEditable(false);
        outputDirTxtField.setText(org.openide.util.NbBundle.getMessage(ClusteringVisualPanel1.class, "ClusteringVisualPanel1.outputDirTxtField.text")); // NOI18N

        numNodesTxtField.setBackground(new java.awt.Color(255, 255, 255));
        numNodesTxtField.setText(org.openide.util.NbBundle.getMessage(ClusteringVisualPanel1.class, "ClusteringVisualPanel1.numNodesTxtField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(ClusteringVisualPanel1.class, "ClusteringVisualPanel1.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(ClusteringVisualPanel1.class, "ClusteringVisualPanel1.jLabel2.text")); // NOI18N

        clusters_1TxtField.setBackground(new java.awt.Color(255, 255, 255));
        clusters_1TxtField.setText(org.openide.util.NbBundle.getMessage(ClusteringVisualPanel1.class, "ClusteringVisualPanel1.clusters_1TxtField.text")); // NOI18N

        clusters_2TxtField.setBackground(new java.awt.Color(255, 255, 255));
        clusters_2TxtField.setText(org.openide.util.NbBundle.getMessage(ClusteringVisualPanel1.class, "ClusteringVisualPanel1.clusters_2TxtField.text")); // NOI18N

        clusters_3TxtField.setBackground(new java.awt.Color(255, 255, 255));
        clusters_3TxtField.setText(org.openide.util.NbBundle.getMessage(ClusteringVisualPanel1.class, "ClusteringVisualPanel1.clusters_3TxtField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(ClusteringVisualPanel1.class, "ClusteringVisualPanel1.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(ClusteringVisualPanel1.class, "ClusteringVisualPanel1.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(ClusteringVisualPanel1.class, "ClusteringVisualPanel1.jLabel5.text")); // NOI18N

        swrmCmdOptsTxtField.setBackground(new java.awt.Color(255, 255, 255));
        swrmCmdOptsTxtField.setText(org.openide.util.NbBundle.getMessage(ClusteringVisualPanel1.class, "ClusteringVisualPanel1.swrmCmdOptsTxtField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(ClusteringVisualPanel1.class, "ClusteringVisualPanel1.jLabel7.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(ClusteringVisualPanel1.class, "ClusteringVisualPanel1.jLabel8.text")); // NOI18N

        jobsPerNodeTxtField.setBackground(new java.awt.Color(255, 255, 255));
        jobsPerNodeTxtField.setText(org.openide.util.NbBundle.getMessage(ClusteringVisualPanel1.class, "ClusteringVisualPanel1.jobsPerNodeTxtField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(verboseChkBox, org.openide.util.NbBundle.getMessage(ClusteringVisualPanel1.class, "ClusteringVisualPanel1.verboseChkBox.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(outputDirButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mapDirButton, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mapDirTxtField)
                                    .addComponent(outputDirTxtField)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(distTestComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel2)))
                                .addGap(108, 108, 108)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(numNodesTxtField)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(verboseChkBox)
                                .addGap(52, 52, 52))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jobsPerNodeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(swrmCmdOptsTxtField)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel7)
                                .addGap(0, 281, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clusters_3TxtField)
                    .addComponent(clusters_2TxtField)
                    .addComponent(clusters_1TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mapDirButton)
                    .addComponent(mapDirTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputDirTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputDirButton))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(distTestComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numNodesTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verboseChkBox))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clusters_1TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clusters_2TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clusters_3TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jobsPerNodeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(swrmCmdOptsTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mapDirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapDirButtonActionPerformed
        String mapFolder = SimSearchUtilities.getDirChoose(lastDir, "Mapped Database Directory", SimSearchUtilities.DIRECTORIES, null);
        if (mapFolder != null) {
            mapDirTxtField.setText(mapFolder);
        }
    }//GEN-LAST:event_mapDirButtonActionPerformed

    private void outputDirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputDirButtonActionPerformed
        String outputFolder = SimSearchUtilities.getDirChoose(lastDir, "Output Directory", SimSearchUtilities.DIRECTORIES, null);
        if (outputFolder != null) {
            outputDirTxtField.setText(outputFolder);
        }
    }//GEN-LAST:event_outputDirButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField clusters_1TxtField;
    private javax.swing.JTextField clusters_2TxtField;
    private javax.swing.JTextField clusters_3TxtField;
    private javax.swing.JComboBox distTestComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jobsPerNodeTxtField;
    private javax.swing.JButton mapDirButton;
    private javax.swing.JTextField mapDirTxtField;
    private javax.swing.JTextField numNodesTxtField;
    private javax.swing.JButton outputDirButton;
    private javax.swing.JTextField outputDirTxtField;
    private javax.swing.JTextField swrmCmdOptsTxtField;
    private javax.swing.JCheckBox verboseChkBox;
    // End of variables declaration//GEN-END:variables

    String getClusters(int num){
        String rval = null;
        switch(num){
            case 1:
                rval = clusters_1TxtField.getText();
                break;
            case 2:
                rval = clusters_2TxtField.getText();
                break;
            case 3:
                rval = clusters_3TxtField.getText();
                break;
        }
        return rval;
    }
    
    String getJobsPerNode(){
        return jobsPerNodeTxtField.getText();
    }
    
    String getOutputDir(){
        return outputDirTxtField.getText();
    }
    
    String getMapDir(){
        return mapDirTxtField.getText();
    }
    
    String getDistTest(){
        return (String) distTestComboBox.getSelectedItem();
    }
    
    String getSwarmCmdOpts(){
        return swrmCmdOptsTxtField.getText();
    }
    
    String getNumNodes(){
        return numNodesTxtField.getText();
    }
    
    boolean getVerbosity(){
        return verboseChkBox.isSelected();
    }

}



