/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.boisestate.SimSearcher;

import javax.swing.JPanel;

public final class QueryVisualPanel1 extends JPanel {
    
    private final String homeDir;

    /**
     * Creates new form QueryVisualPanel1
     */
    public QueryVisualPanel1() {
        initComponents();
        homeDir = System.getProperty("user.home");
        for(String dist_metric : SimSearchUtilities.similarity_metrics){
            distTestComboBox.addItem(dist_metric);
        }
        distTestComboBox.addItem(SimSearchUtilities.FUNCTIONAL_GROUPS);
    }

    @Override
    public String getName() {
        return "Query Driver";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        distTestComboBox = new javax.swing.JComboBox();
        searchDirTxtField = new javax.swing.JTextField();
        QueryFileTxtField = new javax.swing.JTextField();
        searchDirButton = new javax.swing.JButton();
        QueryFileButton = new javax.swing.JButton();
        numTopTxtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(QueryVisualPanel1.class, "QueryVisualPanel1.jLabel2.text")); // NOI18N

        searchDirTxtField.setEditable(false);
        searchDirTxtField.setText(org.openide.util.NbBundle.getMessage(QueryVisualPanel1.class, "QueryVisualPanel1.searchDirTxtField.text")); // NOI18N

        QueryFileTxtField.setEditable(false);
        QueryFileTxtField.setText(org.openide.util.NbBundle.getMessage(QueryVisualPanel1.class, "QueryVisualPanel1.QueryFileTxtField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(searchDirButton, org.openide.util.NbBundle.getMessage(QueryVisualPanel1.class, "QueryVisualPanel1.searchDirButton.text")); // NOI18N
        searchDirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDirButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(QueryFileButton, org.openide.util.NbBundle.getMessage(QueryVisualPanel1.class, "QueryVisualPanel1.QueryFileButton.text")); // NOI18N
        QueryFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QueryFileButtonActionPerformed(evt);
            }
        });

        numTopTxtField.setBackground(new java.awt.Color(255, 255, 255));
        numTopTxtField.setText(org.openide.util.NbBundle.getMessage(QueryVisualPanel1.class, "QueryVisualPanel1.numTopTxtField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(QueryVisualPanel1.class, "QueryVisualPanel1.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(QueryFileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchDirButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchDirTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                    .addComponent(QueryFileTxtField))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(distTestComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)))
                .addGap(229, 229, 229)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numTopTxtField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchDirButton)
                    .addComponent(searchDirTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QueryFileTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QueryFileButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(distTestComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numTopTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(201, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchDirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDirButtonActionPerformed
        String srchFolder = SimSearchUtilities.getDirChoose(homeDir, "Clustered Database Directory", SimSearchUtilities.DIRECTORIES, null);
        if (srchFolder != null) {
            searchDirTxtField.setText(srchFolder);
        }
    }//GEN-LAST:event_searchDirButtonActionPerformed

    private void QueryFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QueryFileButtonActionPerformed
        String[] extensions = {"sdf"};
        String queryFile = SimSearchUtilities.getDirChoose(homeDir, "Query Molecule's sdf file", "structure data files", extensions);
        if(queryFile != null) {
            QueryFileTxtField.setText(queryFile);
        }
    }//GEN-LAST:event_QueryFileButtonActionPerformed

    protected String getQueryFile(){
        return QueryFileTxtField.getText();
    }
    
    protected String getSearchDir(){
        return searchDirTxtField.getText();
    }
    
    protected String getDistTest(){
        return (String) distTestComboBox.getSelectedItem();
    }
    
    protected String getNumTopResults(){
        return numTopTxtField.getText();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton QueryFileButton;
    private javax.swing.JTextField QueryFileTxtField;
    private javax.swing.JComboBox distTestComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField numTopTxtField;
    private javax.swing.JButton searchDirButton;
    private javax.swing.JTextField searchDirTxtField;
    // End of variables declaration//GEN-END:variables
}
